name: Security

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  security:
    uses: bookmd/security-scanner/.github/workflows/security-scan.yml@v1
    secrets: inherit
